version: 2
updates:
  # Infrastructure
  ## GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files in `.github/workflows` (default) and
    # composite actions under `.github/actions`
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    groups:
      gh-actions:
        #applies-to: version-updates
        patterns: ["*"]
    commit-message:
      prefix: "deps(ci)"
