# WSL doesn't expose a TPM device, but worse than that is the fact that this unit respawns many
# times while WSL is assembling the device tree, wasting resources and causing the system to go
# degraded because of the systemd builtin anti-flapping guard.
[Unit]
ConditionVirtualization=!wsl
